language: java
jdk:
  - oraclejdk8
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B
after_success:
  - mvn clean test jacoco:report coveralls:report
addons:
  apt:
    packages:
      - oracle-java9-installer